import { each, esc } from '../../_lib/html.js';
import { constraints, experiments, lab } from '../data.js';
import { studio } from '../../../site.config.js';
import { crumbs } from '../components.js';

export const meta = {
  title: 'Colophon — Lab',
  description: `How the lab is built and what it deliberately leaves out: no rendering
    engine, no physics engine, no scroll library, and no exemption from accessibility.`,
  scripts: ['ui.js'],
  breadcrumbs: [
    { label: 'Work', href: '/' },
    { label: 'Lab', href: '/lab/' },
    { label: 'Colophon', href: '/lab/colophon/' },
  ],
};

/** What each experiment would normally have cost, in library weight. */
const AVOIDED = [
  ['three.js', '~600 KB', 'Renderer'],
  ['matter.js', '~90 KB', 'Verlet'],
  ['GSAP + ScrollTrigger', '~120 KB', 'Descent'],
  ['A smooth-scroll library', '~25 KB', 'Descent'],
];

export function render({ url }) {
  return `
<section class="section--tight" style="padding-top:var(--s-l)">
  <div class="shell">
    ${crumbs(
      [
        { label: 'Lab', href: '/lab/' },
        { label: 'Colophon', href: '/lab/colophon/' },
      ],
      url,
    )}
    <p class="label">Colophon</p>
    <h1 class="h1" style="margin-top:var(--s-2xs)">How this is built.</h1>
    <p class="lede" style="margin-top:var(--s-s)">${esc(lab.lede)}</p>
  </div>
</section>

<section class="section ruled" aria-labelledby="rules-heading">
  <div class="shell">
    <h2 class="label" id="rules-heading">The rules</h2>
    <div class="notes" style="margin-top:var(--s-l)">
      ${each(
        constraints,
        (rule) => `<div>
        <h3 class="note__title">${esc(rule.title)}</h3>
        <p class="prose" style="margin:0">${esc(rule.text)}</p>
      </div>`,
      )}
    </div>
  </div>
</section>

<section class="section ruled" aria-labelledby="weight-heading">
  <div class="shell">
    <h2 class="label" id="weight-heading">What was not shipped</h2>
    <p class="prose" style="margin-top:var(--s-s)">
      Not an argument that these libraries are bad — they are excellent, and on a project
      with a deadline most of them are the right call. The point is that writing the thing
      yourself is the only way to find out whether you could.
    </p>

    <table class="readout-table" style="max-width:44rem;margin-top:var(--s-l)">
      <caption>Libraries the experiments would normally have needed</caption>
      <thead>
        <tr>
          <th scope="col">Library</th>
          <th scope="col">Typical weight</th>
          <th scope="col">Replaced in</th>
        </tr>
      </thead>
      <tbody>
        ${each(
          AVOIDED,
          ([name, weight, where]) => `<tr>
          <th scope="row">${esc(name)}</th>
          <td>${esc(weight)}</td>
          <td>${esc(where)}</td>
        </tr>`,
        )}
      </tbody>
    </table>
  </div>
</section>

<section class="section ruled" aria-labelledby="stack-heading">
  <div class="shell">
    <h2 class="label" id="stack-heading">The stack, such as it is</h2>
    <div class="prose" style="margin-top:var(--s-s)">
      <p>Static HTML generated by a dependency-free Node script. Plain CSS with custom
        properties. ES modules served directly to the browser — no bundler, no transpiler,
        no build step beyond writing files out.</p>
      <p>The whole portfolio, all five sites, is under two megabytes. The lab's four
        experiments add roughly <strong>30 KB of JavaScript</strong> between them, which is
        less than the smallest library any one of them replaces.</p>
      <p>Every page is checked before it ships: broken links, metadata, heading structure,
        structured data, form labelling and unlabelled graphics all fail the build. The
        experiments are additionally driven end to end in a real browser.</p>
    </div>
  </div>
</section>

<section class="section ruled" aria-labelledby="honest-heading">
  <div class="shell">
    <h2 class="label" id="honest-heading">Where the seams are</h2>
    <div class="prose" style="margin-top:var(--s-s)">
      <p><strong>The renderer has no shadow mapping, no post-processing and no scene
        graph.</strong> It renders one object well. An engine gives you all three on day one,
        and for anything with more than a handful of objects that is the correct trade.</p>
      <p><strong>The physics is 2D and position-based.</strong> No rigid bodies, no rotation,
        no continuous collision detection. It is the right tool for cloth and rope and the
        wrong one for a stack of crates.</p>
      <p><strong>Two of the four experiments need JavaScript to show anything.</strong> The
        renderer and the physics degrade to an explanation rather than a demo. Descent and
        Motion both work without it.</p>
      <p>Naming these is the point of a colophon. Work that only lists what it does well is
        advertising.</p>
    </div>
  </div>
</section>

<section class="section--tight ruled">
  <div class="shell" style="display:flex;flex-wrap:wrap;gap:var(--s-s);align-items:center;
                            justify-content:space-between">
    <p class="dim" style="font-size:var(--step--1);max-width:52ch">
      ${esc(lab.name)} is in-house research by ${esc(studio.name)}. The client work is on the
      studio site.
    </p>
    <div style="display:flex;flex-wrap:wrap;gap:var(--s-2xs)">
      <a class="btn btn--ghost" href="${esc(url('/lab/'))}">Back to the lab</a>
      <a class="btn" href="${esc(url('/'))}">See the client work</a>
    </div>
  </div>
</section>
`;
}
